name: last_mile_tracker
description: "Last Mile Tracker"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  
  # Database (Offline-First)
  drift: ^2.31.0
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.1
  
  # BLE
  flutter_blue_plus: ^2.1.0
  permission_handler: ^12.0.1
  
  # Networking
  connectivity_plus: ^7.0.0
  share_plus: ^12.0.1
  
  # Supabase (Future)
  supabase_flutter: ^2.8.4
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_animate: ^4.5.2
  flutter_secure_storage: ^10.0.0
  firebase_core: ^4.4.0
  firebase_crashlytics: ^5.0.7
  lmt_models:
    path: ../../packages/lmt_models
  http: ^1.2.2
  package_info_plus: ^9.0.0
  flutter_map_marker_popup: ^8.1.0
  flutter_map_animations: ^0.9.0
  geolocator: ^14.0.2
  json_annotation: ^4.9.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4
  riverpod: ^3.1.0
  collection: ^1.19.1
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.6.1
  drift_dev: ^2.31.0
  riverpod_generator: any
  json_serializable: ^6.11.2


flutter:

  uses-material-design: true
