[project]
name = "firmware_esp32"
version = "0.1.0"
description = "ESP32 MicroPython firmware for Last Mile Tracker"
readme = "README.md"

[tool.ruff]
target-version = "py312"
line-length = 99
src = ["."]

[tool.ruff.format]
quote-style = "double"
